quarkus.datasource.jdbc.driver=com.mysql.cj.jdbc.Driver
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=mysql
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3336/lista_spesa_db

quarkus.hibernate-orm.log.sql=true
quarkus.http.cors=true
quarkus.hibernate-orm.database.generation=update
quarkus.http.cors.origins[*]=http://localhost:4200
quarkus.http.cors.origins=http://localhost:4200
mp.jwt.verify.publickey.location=keys/publicKey.pem
mp.jwt.verify.issuer=https://quarkus.io/issuer

